test-errors
testSlaveExceptionFailsTest
	<expectedFailure>
	
	self with: #slave do: [ self error ]